baseURL = "/"
title = "Sunnie Sunday Report"
publishDir = "output"

# Use commit time to update the sitemap
enableGitInfo = true
enableRobotsTXT = true

disableKinds = ["taxonomy", "term", "RSS"]

[markup.goldmark.extensions.typographer]
  disable = true

# Chroma syntax highlighting for docs code blocks
[markup.highlight]
  noClasses = false
  style = "bw"

# Suppress individual character pages
[[cascade]]
  [cascade.build]
    render = "never"
  [cascade.target]
    kind = "section"
    path = "/characters"

[[cascade]]
  [cascade.build]
    render = "never"
  [cascade.target]
    kind = "page"
    path = "/characters/**"

[params]
  author = "/xivg/"
  # One of the files in static/css/themes/, without the .css extension
  colorTheme = "sonokai-dark"
